import type { NextPage } from 'next';
import Head from 'next/head';

import  { iCard } from '@/element/Card/Card';
import { iSpecialCard, Colors } from '@/element/SpecialCard/SpecialCard';
import { Slide } from '@/components/element/Carousel/Carousel';

import Storefront from '@/template/Home/Storefront';

const Home: NextPage = () => {

  const DUMMY_SLIDES: Slide[] = [
    {
      id: '1',
      url: "/images/ameen-almayuf-OQ4tJVXMCYM-unsplash.jpg"
    },
    {
      id: '2',
      url: "/images/daniel-romero-q-RQba-XCgU-unsplash.jpg"
    },
    {
      id: '3',
      url: "/images/omid-armin-aV3c3oJ9hZM-unsplash.jpg"
    },
    {
      id: '4',
      url: "/images/balazs-ketyi-mQFUoE6dtpY-unsplash.jpg"
    }
  ];

  const DUMMY_ITEMS: iCard[] = [
    {
      id: '1',
      title: 'هدفون بی‌سیم اپل مدل ایرپاد پرو',
      image: '/images/airpods-71zny7BTRlL._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۵۰۰،۰۰۰',
      off: '۶۵۰،۰۰۰'
    },
    {
      id: '2',
      title: 'پایه موبایل برند لمیکال مدل ۲',
      image: '/images/Lamical-61dpRC+gl3L._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۱،۱۴۵،۰۰۰',
      
    },
    {
      id: '3',
      title: 'اسپیکر خانگی برند هارمان کاردون مدل سفینه‌ای',
      image: '/images/harman-kardon613y-XeXlSL._AC_SL1500.jpg',
      category: 'لوازم صوتی و تصویری',
      price: '۶،۸۳۴،۰۰۰'
    },
    {
      id: '4',
      title: 'ساعت هوشمند اپل سری ۶ رنگ آبی عمیق',
      image: '/images/apple-watch-71bf9IpGjtL._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۹،۱۶۲،۰۰۰'
    }
  ];

  const DUMMY_SPECIAL_ITEMS: iSpecialCard[] = [
    {
      title: 'ساعت‌های هوشمند سامسونگ',
      subtitle: 'ساعت چنده؟',
      image: '/images/samsung-gear-s3.png',
      color: Colors.Blue
    },
    {
      title: 'هدفون استودیوی آدیو تکنیکا',
      subtitle: 'صدایی که تا حالا نشنیدی',
      image: '/images/ath-m50x_01a.png',
    },
  ];

   const DUMMY_SPECIAL_ITEMS_2: iSpecialCard[] = [
    {
      title: 'ماوس گیمینگ ریزر سری دث ادر',
      subtitle: 'برای رقابت آماده باش',
      image: '/images/razer-mouse.png',
      color: Colors.Cyan
    },
    {
      title: 'پرینتر اچ پی مدل لیزر جت',
      subtitle: 'مناسب برای هر جا',
      image: '/images/hp-printer.png',
      color: Colors.Orange
    },
  ];

  return (
    <>
      <Head>
        <title>Electro - Digital Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Storefront slides={DUMMY_SLIDES} items={DUMMY_ITEMS} specialItems={DUMMY_SPECIAL_ITEMS} specialItemsAgain={DUMMY_SPECIAL_ITEMS_2} />
     </>
  )
}

export default Home
