import type { NextPage } from 'next'
import Head from 'next/head'

// Layouts and Components
import Card, { Banner, iCard } from '@/components/modules/Card/Card';
import { iSpecialCard, Colors } from '@/components/modules/SpecialCard/SpecialCard';

import ProductRow from '@/components/layout/ProductRow/ProductRow';
import SpecialRow from '@/components/layout/SpecialRow/SpecialRow';
import ProductGrid from '@/components/layout/ProductGrid/ProductGrid';

import styles from '../app/styles/pages/Home.module.scss';

const Home: NextPage = () => {

  const DUMMY_ITEMS: iCard[] = [
    {
      id: '1',
      title: 'هدفون بی‌سیم اپل مدل ایرپاد پرو',
      image: '/images/airpods-71zny7BTRlL._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۵۰۰،۰۰۰',
      off: '۶۵۰،۰۰۰'
    },
    {
      id: '2',
      title: 'پایه موبایل برند لمیکال مدل ۲',
      image: '/images/Lamical-61dpRC+gl3L._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۱،۱۴۵،۰۰۰',
      
    },
    {
      id: '3',
      title: 'اسپیکر خانگی برند هارمان کاردون مدل سفینه‌ای',
      image: '/images/harman-kardon613y-XeXlSL._AC_SL1500.jpg',
      category: 'لوازم صوتی و تصویری',
      price: '۶،۸۳۴،۰۰۰'
    },
    {
      id: '4',
      title: 'ساعت هوشمند اپل سری ۶ رنگ آبی عمیق',
      image: '/images/apple-watch-71bf9IpGjtL._AC_SL1500.jpg',
      category: 'لوازم جانبی موبایل',
      price: '۹،۱۶۲،۰۰۰'
    }
  ];

  const DUMMY_SPECIAL_ITEMS: iSpecialCard[] = [
    {
      title: 'ساعت‌های هوشمند سامسونگ',
      subtitle: 'ساعت چنده؟',
      image: '/images/samsung-gear-s3.png',
      color: Colors.Blue
    },
    {
      title: 'هدفون استودیوی آدیو تکنیکا',
      subtitle: 'صدایی که تا حالا نشنیدی',
      image: '/images/ath-m50x_01a.png',
    },
  ];

   const DUMMY_SPECIAL_ITEMS_2: iSpecialCard[] = [
    {
      title: 'ماوس گیمینگ ریزر سری دث ادر',
      subtitle: 'برای رقابت آماده باش',
      image: '/images/razer-mouse.png',
      color: Colors.Cyan
    },
    {
      title: 'پرینتر اچ پی مدل لیزر جت',
      subtitle: 'مناسب برای هر جا',
      image: '/images/hp-printer.png',
      color: Colors.Orange
    },
  ];

  return (
    <>
      <Head>
        <title>Electro - Digital Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.homeGrid}>
        <div className={styles.hero}>
          <div className={styles.heroSlider}>
            
          </div>
          <div className={styles.heroProduct}>
            <Card
              id="1"
              category="کیف و کاور موبایل"
              title="قاب محافظ سیلیکونی سامسونگ مناسب برای گوشی سامسونگ S21"
              price="۱۴۹،۰۰۰"
              image="/images/samsung-case-5151hc1ZTFS._AC_SL1500_.jpg"
              banner={Banner.Popular}
            />
          </div>
        </div>
      
        <div className={styles.sale}>
          <ProductRow title="تخفیفات هیجان انگیز" items={DUMMY_ITEMS} />
        </div>

        <div className={styles.special}>
          <SpecialRow items={DUMMY_SPECIAL_ITEMS} />
        </div>

        <div className={styles.browse}>
          <ProductGrid title="برترین‌ها" items={DUMMY_ITEMS} />
        </div>

        <div className={styles.why}>
          <div className={styles.whyBackground}>
            <div className={styles.whyText}>
              <p>بیش از ۱۵۰۰ نفر در ۱۵ سال به ما اعتماد کردند</p>
              <span>دلیل این انتخاب چه بوده؟</span>
              <ul>
                <li>تضیمن قیمت</li>
                <li>تضیمن کیفیت</li>
                <li>تضیمن ارسال</li>
                <li>تضیمن سلامت</li>
              </ul>
            </div>
          </div>
          <div className={styles.whyOverlay}>
          </div>
        </div>

        <div className={styles.recommended}>
          <ProductRow title="پیشنهاد شده برای شما" items={DUMMY_ITEMS} />
        </div>

        <div className={styles.specialAgain}>
          <SpecialRow items={DUMMY_SPECIAL_ITEMS_2} />
        </div>

        <div className={styles.scroll}>
          
        </div>
      
      </main>

     </>
  )
}

export default Home
